import { Rubik_Wet_Paint } from "next/font/google";
import "./globals.css";

const rubikwp = Rubik_Wet_Paint({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-rubikwp"
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={rubikwp.variable}>
        {children}
      </body>
    </html>
  );
}
